baseURL = 'https://crispybaccoon.github.io/mocha'
Author = 'crispybaccoon'
languageCode = 'en-us'
title = 'mocha'
theme = 'mocha-theme'

enableEmoji = true

[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    pre = "pen-tool"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Docs"
    pre = ""
    url = "/doc/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 3